<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="0" name="Failed suite [Surefire suite]">
  <test thread-count="1" verbose="0" name="Surefire test(failed)">
    <classes>
      <class name="com.salesforcetest.test.NewAccountScenarioTest">
        <methods>
          <include name="getResult"/>
          <include name="init"/>
          <include name="inject_reporter"/>
          <include name="test_create_internal_account"/>
          <include name="flushReporter"/>
        </methods>
      </class> <!-- com.salesforcetest.test.NewAccountScenarioTest -->
      <class name="com.salesforcetest.test.PrivacyNoticeServiceItemTest">
        <methods>
          <include name="flushReporter"/>
          <include name="init"/>
          <include name="inject_reporter"/>
          <include name="create_pn_service_item_manually_test_Scenario_14_1"/>
          <include name="getResult"/>
        </methods>
      </class> <!-- com.salesforcetest.test.PrivacyNoticeServiceItemTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
