<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="52521" started-at="2019-02-16T07:45:01Z" finished-at="2019-02-16T07:45:54Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="52521" started-at="2019-02-16T07:45:01Z" finished-at="2019-02-16T07:45:54Z">
      <class name="com.salesforcetest.test.NewAccountScenarioTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.salesforcetest.test.NewAccountScenarioTest@6933b6c6]" name="init" is-config="true" duration-ms="12339" started-at="2019-02-16T07:45:35Z" finished-at="2019-02-16T07:45:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="test_create_internal_account()[pri:1, instance:com.salesforcetest.test.NewAccountScenarioTest@6933b6c6]" name="test_create_internal_account" duration-ms="6010" started-at="2019-02-16T07:45:48Z" description="Scenario 1.1 and 1.2" finished-at="2019-02-16T07:45:54Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[chrome not reachable
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'DESKTOP-IUQKEJS', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\Zaim3\AppData\Loca...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:49452}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 72.0.3626.109, webStorageEnabled: true}
Session ID: f2a16bf2142188cbb498d1103ae88f5d]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'DESKTOP-IUQKEJS', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\Zaim3\AppData\Loca...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:49452}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 72.0.3626.109, webStorageEnabled: true}
Session ID: f2a16bf2142188cbb498d1103ae88f5d
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276)
at com.salesforcetest.test.NewAccountScenarioTest.test_create_internal_account(NewAccountScenarioTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:224)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_internal_account -->
        <test-method status="PASS" signature="inject_reporter(java.lang.reflect.Method)[pri:0, instance:com.salesforcetest.test.NewAccountScenarioTest@6933b6c6]" name="inject_reporter" is-config="true" duration-ms="0" started-at="2019-02-16T07:45:48Z" finished-at="2019-02-16T07:45:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.salesforcetest.test.NewAccountScenarioTest.test_create_internal_account()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inject_reporter -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.salesforcetest.test.NewAccountScenarioTest@6933b6c6]" name="getResult" is-config="true" duration-ms="0" started-at="2019-02-16T07:45:54Z" finished-at="2019-02-16T07:45:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_create_internal_account status=FAILURE method=NewAccountScenarioTest.test_create_internal_account()[pri:1, instance:com.salesforcetest.test.NewAccountScenarioTest@6933b6c6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.salesforcetest.test.NewAccountScenarioTest -->
      <class name="com.salesforcetest.test.PrivacyNoticeServiceItemTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.salesforcetest.test.PrivacyNoticeServiceItemTest@7d3e8655]" name="init" is-config="true" duration-ms="12042" started-at="2019-02-16T07:45:01Z" finished-at="2019-02-16T07:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="inject_reporter(java.lang.reflect.Method)[pri:0, instance:com.salesforcetest.test.PrivacyNoticeServiceItemTest@7d3e8655]" name="inject_reporter" is-config="true" duration-ms="2" started-at="2019-02-16T07:45:14Z" finished-at="2019-02-16T07:45:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.salesforcetest.test.PrivacyNoticeServiceItemTest.create_pn_service_item_manually_test_Scenario_14_1() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inject_reporter -->
        <test-method status="FAIL" signature="create_pn_service_item_manually_test_Scenario_14_1()[pri:1, instance:com.salesforcetest.test.PrivacyNoticeServiceItemTest@7d3e8655]" name="create_pn_service_item_manually_test_Scenario_14_1" duration-ms="21680" started-at="2019-02-16T07:45:14Z" description="Scenario 14.1 - Create a Privacy Notice Service Item" finished-at="2019-02-16T07:45:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Passed] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Passed] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.salesforcetest.main.MultiTypeServiceItemCreator.create_privacy_service_item_manually(MultiTypeServiceItemCreator.java:133)
at com.salesforcetest.test.PrivacyNoticeServiceItemTest.create_pn_service_item_manually_test_Scenario_14_1(PrivacyNoticeServiceItemTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:224)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_pn_service_item_manually_test_Scenario_14_1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.salesforcetest.test.PrivacyNoticeServiceItemTest@7d3e8655]" name="getResult" is-config="true" duration-ms="1" started-at="2019-02-16T07:45:35Z" finished-at="2019-02-16T07:45:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=create_pn_service_item_manually_test_Scenario_14_1 status=FAILURE method=PrivacyNoticeServiceItemTest.create_pn_service_item_manually_test_Scenario_14_1()[pri:1, instance:com.salesforcetest.test.PrivacyNoticeServiceItemTest@7d3e8655] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.salesforcetest.test.PrivacyNoticeServiceItemTest -->
      <class name="com.salesforcetest.test.ReportingTest">
        <test-method status="PASS" signature="reportTest()[pri:1, instance:com.salesforcetest.test.ReportingTest@7dfb0c0f]" name="reportTest" duration-ms="0" started-at="2019-02-16T07:45:35Z" description="Scenario 2.1" finished-at="2019-02-16T07:45:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportTest -->
        <test-method status="PASS" signature="getResult()[pri:0, instance:com.salesforcetest.test.ReportingTest@7dfb0c0f]" name="getResult" is-config="true" duration-ms="1" started-at="2019-02-16T07:45:35Z" finished-at="2019-02-16T07:45:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="flushReport()[pri:0, instance:com.salesforcetest.test.ReportingTest@7dfb0c0f]" name="flushReport" is-config="true" duration-ms="136" started-at="2019-02-16T07:45:54Z" finished-at="2019-02-16T07:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.salesforcetest.test.ReportingTest@7dfb0c0f]" name="endReport" is-config="true" duration-ms="1505" started-at="2019-02-16T07:45:54Z" finished-at="2019-02-16T07:45:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.salesforcetest.test.ReportingTest -->
      <class name="com.salesforcetest.test.StartTest">
        <test-method status="PASS" signature="kill_chrome_driver_instance()[pri:0, instance:com.salesforcetest.test.StartTest@626abbd0]" name="kill_chrome_driver_instance" duration-ms="290" started-at="2019-02-16T07:45:01Z" finished-at="2019-02-16T07:45:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kill_chrome_driver_instance -->
      </class> <!-- com.salesforcetest.test.StartTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
